ns_args:
  data_root: 'nuscenes'
  version: 'v1.0-mini'
  verbose: yes

  history_duration: 4 # tau
  prediction_duration: 12 # h
  nb_lane_candidates: 6 # N
  number_of_predictions: 8 # K
  batch_size: 32 # 32
  lane_amount_of_coordinates: 150
  forward_lane: 100
  backward_lane: 30
  precision_lane: 0.5
  num_heads: 8
  lr: 0.0001
  # TODO: Explain those
  hidden_size: 64
  nb_columns: 2
  num_epochs: 20
  log_dir: './results'
  steps_to_log_train_loss: 100
  alpha: 0.3
  beta: 0.7

# LaneNet arguments
ln_args:
  use_cuda: no
  number_of_predictions: 8 # K
  train_flag: yes