ns_args:
  data_root: 'nuscenes'
  version: 'v1.0-trainval'
  split: 'mini_train'
  verbose: yes
  history_duration: 4 # tau
  prediction_duration: 12 # h
  lane_amount_of_coordinates: 150
  forward_lane: 100
  backward_lane: 30
  precision_lane: 0.5
  nb_coordinates: 2
  num_epochs: 20
  log_dir: './results'
  steps_to_log_train_loss: 100
  length_lane: 130

argo_args:
  data_root: 'nuscenes'
  version: 'v1.0-mini'
  verbose: yes
  split: 'mini_train'
  history_duration: 20 # tau
  prediction_duration: 30 # h
  lane_amount_of_coordinates: 150
  forward_lane: 50
  backward_lane: 30
  precision_lane: 1.0
  nb_coordinates: 2
  log_dir: './results/argoverse'
  steps_to_log_train_loss: 100

# LaneNet arguments
ln_args:
  use_cuda: no
  number_of_predictions: 1 # K
  nb_lane_candidates: 6 # N
  train_flag: yes
  dropout: 0.1
  batch_size: 32 # 32
  lr: 0.0003
  num_epochs: 20
  alpha: 0.3
  beta: 0.7
  weight_decay: 0.0
  model_dir: 'experiments/'
